#!/usr/bin/env bash

NODE_EXPORTER="./bin/node_exporter"

case "$1" in
    run)
        "$NODE_EXPORTER"
        ;;

    trio1)
        "$NODE_EXPORTER" --web.listen-address 127.0.0.1:8701
        ;;

    trio2)
        "$NODE_EXPORTER" --web.listen-address 127.0.0.1:8702
        ;;

    trio3)
        "$NODE_EXPORTER" --web.listen-address 127.0.0.1:8703
        ;;

    *)
        echo "No command given"
        ;;
esac
