#!/usr/bin/env bash

PROMETHEUS="./bin/prometheus-3.0.0.linux-amd64/prometheus"

case "$1" in
    run)
        "$PROMETHEUS" --config.file=prometheus.yml
        ;;

    *)
        echo "No command given"
        ;;
esac
